"use client";

import { FormEvent, useMemo, useState } from "react";
import { SellerNav } from "@/components/SellerNav";
import { won } from "@/utils/format";

export default function NewSellerProductPage() {
  const [values,setValues] = useState({ original:30000,start:27000,min:18000,stepPeople:5,stepAmount:1000,maxPeople:50 });
  const [saved,setSaved] = useState(false);
  const steps = useMemo(()=>Array.from({ length:Math.min(7,Math.ceil(values.maxPeople/values.stepPeople)) },(_,i)=>({ people:i*values.stepPeople, price:Math.max(values.min,values.start-i*values.stepAmount) })),[values]);
  const number = (key:keyof typeof values) => (event:React.ChangeEvent<HTMLInputElement>) => setValues({...values,[key]:Number(event.target.value)});
  const submit = (event:FormEvent) => { event.preventDefault(); setSaved(true); };
  return <div className="seller-shell"><SellerNav/><div className="seller-content"><span className="eyebrow">Create group deal</span><h1 className="page-title">새 공동구매 등록</h1><p className="page-lead">가격 하락 규칙을 입력하면 참여 단계별 가격을 미리 계산합니다.</p><form onSubmit={submit} className="content-grid" style={{ marginTop:28,alignItems:"start" }}><div className="panel"><div className="form-grid"><div className="form-group full"><label>상품명</label><input className="field" placeholder="상품명을 입력하세요" required/></div><div className="form-group full"><label>상품 설명</label><textarea className="field" placeholder="상품과 공동구매를 소개해주세요."/></div><div className="form-group"><label>상품 타입</label><select className="field"><option>일반 공동구매</option><option>재고떨이 상품</option></select></div><div className="form-group"><label>판매자명</label><input className="field" defaultValue="DropDeal 파트너"/></div><div className="form-group"><label>정가</label><input className="field" type="number" value={values.original} onChange={number("original")}/></div><div className="form-group"><label>공동구매 시작가</label><input className="field" type="number" value={values.start} onChange={number("start")}/></div><div className="form-group"><label>최저 판매가</label><input className="field" type="number" value={values.min} onChange={number("min")}/></div><div className="form-group"><label>최대 참여 인원</label><input className="field" type="number" value={values.maxPeople} onChange={number("maxPeople")}/></div><div className="form-group"><label>몇 명마다 가격 하락</label><input className="field" type="number" value={values.stepPeople} onChange={number("stepPeople")}/></div><div className="form-group"><label>단계당 할인 금액</label><input className="field" type="number" value={values.stepAmount} onChange={number("stepAmount")}/></div><div className="form-group"><label>총 재고 수량</label><input className="field" type="number" defaultValue="50"/></div><div className="form-group"><label>최소 참여 인원</label><input className="field" type="number" defaultValue="15"/></div><div className="form-group full"><label><input type="checkbox"/> 재고떨이 랜덤 50% 쿠폰 이벤트 사용</label></div></div><button className="btn btn-primary" style={{ marginTop:20,width:"100%" }}>{saved ? "Mock 상품 등록 완료" : "공동구매 등록하기"}</button></div><aside className="policy-preview"><span className="eyebrow" style={{ color:"var(--lime)" }}>Price policy preview</span><h3>가격 단계 미리보기</h3>{steps.map(step=><div className="policy-step" key={step.people}><span>{step.people}명 참여</span><b>{won(step.price)}</b></div>)}<div className="policy-step"><span>최저 판매가</span><b style={{ color:"var(--lime)" }}>{won(values.min)}</b></div></aside></form></div></div>;
}
